import express from 'express';
import { getAlbums } from '../Controllers/getAlbums.js';
import { getArtist } from '../Controllers/getArtist.js';
import { getPartySong } from '../Controllers/getPartySong.js';
import { getProduct } from "../Controllers/GetProduct.js";
import { getRequests } from '../Controllers/getRequest.js';
import { getSearch } from '../Controllers/getSearch.js';
const Routers = express.Router();
Routers.get('/products',getProduct);
Routers.get('/party_song',getPartySong);
Routers.post('/Wish',getRequests);
Routers.get('/search',getSearch);
Routers.get('/artists',getArtist);
Routers.get('/Albums',getAlbums);
export default Routers;